#!/usr/bin/env bash
# Install nginx on your web-01.

sudo apt-get -y update
sudo apt-get -y install nginx

content="Hello World!"

if ! sudo systemctl is-active --quiet nginx; then
    sudo systemctl start nginx
fi

echo "$content" | sudo tee /var/www/html/index.html > /dev/null

sudo service nginx restart
