#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
apt-get -y install haproxy

server_config=\
"
frontend  besthor_frontend
        bind *:80
        mode http
        default_backend besthor_backend
backend besthor_backend
        balance roundrobin
        server 176572-web-01 35.153.231.121:80 check
        server 176572-web-02 54.236.24.144:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy restart
