#!/usr/bin/env bash
# 0. Nginx likes port 80.
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs.
# Write a Bash script that configures a server to the above requirements.
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
